spring.application.name=real-time-chat-app
server.port=8081
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
jwt.secret=Yxzk0SD8bvJMpOy0pWBYjFFZ+4vrx7MWKXPPhE/Aa5o=